name: TestWorkFlow

on:
  schedule:
    - cron:  '0 9 * * *'

jobs:
  main:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'true'
          go-version: '1.17.2'

      - name: Build app
        env: 
          TELEGRAM_API: ${{ secrets.TELEGRAM_API }}
          MESSAGE_ID: ${{ secrets.MESSAGE_ID }}
          NAMEDAYS: ${{ secrets.NAMEDAYS }}
          BIRTHDAYS: ${{ secrets.BIRTHDAYS }}
        run: |
          printf "$NAMEDAYS" > nameday
          printf "$BIRTHDAYS" > birthday

          go build
          ./birthday-telegram-bot ./nameday ./birthday